### ISSUE TITLE
Naming: "network ID" vs. "chain ID"

### ISSUE THREAD

**Issue by webmaster128** [interchain-registry/interchain-registry#12]
For consistent documentation, we should have a consistent name for the `network` field. The two obvious candidates are "network ID" and "chain ID".

We use chain ID at IOV which comes from the name of the field in Tendermint genesis file. But I have no strong opinion here. It should just be consistent.

**Comment by pedrouid** [comment]
Depends what we prioritize, for example EVM uses chainId but most blockchains like Cosmos and Bitcoin use just network.

So I basically just prioritized the majority by converting EVM chainId's into a network string (chainId 1 === network `eip155-1`)

I would signal to keep this field as is

**Comment by webmaster128** [comment]
"network" is fine for me.

But can we go with "network ID" instead of just "network"? The idea behind this is that the _network ID_ uniquely identifies the _network_. The _network ID_ is a string whereas the _network_ is a vague, hard to specify idea of what a network is.

**Comment by pedrouid** [comment]
Alright, that makes sense

**Comment by RiccardoM** [comment]
I'm in favor of adding the `id` suffix as well. It makes it more clear on what the field itself represents.
