### ISSUE TITLE
Generate different list of chains based on the interface type

### ISSUE THREAD

**Issue by RiccardoM** [interchain-registry/interchain-registry#2]
Currently, as far as I see, there is only one list of chains which is present inside the `chains.json` file on the main folder. 

I think that we should separate that list into different lists, maybe grouping them into a specific folder. For example, a structure like this could be easily searchable: 

```
/chains/<interface>.json
```

So, for example, we would have

```
/chains/cosmos.json
/chains/evm.json
```

This could be more useful to clients that want a list of all the chains of a particular interface, without downloading all the data of other interfaces. 

I also think that this could be automated somehow using a script that updates the list on each commit made.

**Comment by pedrouid** [comment]
Fixed on https://github.com/interchain-registry/interchain-registry/commit/1b7067fabb5a5829b2dbc329b13fb167bd894d0d
