### ISSUE TITLE
Remove "id" field

### ISSUE THREAD

**Issue by pedrouid** [interchain-registry/interchain-registry#5]
The registry concerns itself mostly with the network field and the id field was meant to be used as DID to resolve a document part of this registry. However it makes more sense to remove it since DID Documents are meant to be authenticated by the owner but in this scenario we have a community managed registry which is not owned by anyone but maintained by everyone

**Comment by RiccardoM** [comment]
Should we simply delete the `did:` prefix? I think that a unique id is still going to be useful when searching though the chains' list.

**Comment by webmaster128** [comment]
What's the difference between the `id` field (with or without `did:`) and the network ID (`network`)? I think we should drop `id` in favour the network ID.
